[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
ethic_check_core = "6wHSyHiWp6jjUDHDn7o5hydAeBpLD3EB7JbhyrxJPeHH"

[programs.localnet]
ethic_check_core = "6wHSyHiWp6jjUDHDn7o5hydAeBpLD3EB7JbhyrxJPeHH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/kalyonekenobe/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
